
services:
  ashish-mongo:
    image: mongo:7
    container_name: ashish-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ashish
      MONGO_INITDB_ROOT_PASSWORD: Test123
      MONGO_INITDB_DATABASE: ashish_hospital
    ports:
      - "27017:27017"

  web:
    build: .
    container_name: ashish-hospital-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ashish-mongo

